// <auto-generated />
using System;
using Gatekeeper.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gatekeeper.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Gatekeeper.Models.Analyst", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Createdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Createuser")
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Displayname")
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Localname")
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime?>("Moddate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Moduser")
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Regno")
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Role")
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Status")
                        .HasColumnType("varchar(5)");

                    b.HasKey("Id");

                    b.ToTable("analyst", "gkp");
                });

            modelBuilder.Entity("Gatekeeper.Models.Analystnote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Analystid")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Createdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Createuser")
                        .HasColumnType("varchar(45)");

                    b.Property<DateTime?>("Enterdate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Moddate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Moduser")
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Notes")
                        .HasColumnType("varchar(max)");

                    b.Property<int?>("Requestid")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("Supervisorapproved")
                        .HasColumnType("int");

                    b.Property<string>("Supervisornotes")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Timetaken")
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.ToTable("analystnote", "gkp");
                });

            modelBuilder.Entity("Gatekeeper.Models.AuditLog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("AccessDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AccessNiche")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("AccessSystem")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Activity")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("ActivityXml")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OccurrenceNo")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("RegNo")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("Sdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasColumnType("varchar(50)");

                    b.HasKey("ID");

                    b.ToTable("AuditLog", "gkp");
                });

            modelBuilder.Entity("Gatekeeper.Models.Discloseditem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Createdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Createuser")
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Othertext")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Requestid")
                        .HasColumnType("int");

                    b.Property<int>("Sectionid")
                        .HasColumnType("int");

                    b.Property<string>("Sectiontype")
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Status")
                        .HasColumnType("varchar(5)");

                    b.HasKey("Id");

                    b.ToTable("discloseditems", "gkp");
                });

            modelBuilder.Entity("Gatekeeper.Models.Extension", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Createdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Createuser")
                        .HasColumnType("varchar(45)");

                    b.Property<int?>("Dayamount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Extensiondate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Extensionid")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Moddate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Moduser")
                        .HasColumnType("varchar(45)");

                    b.Property<int?>("Requestid")
                        .HasColumnType("int");

                    b.Property<int?>("Sectionid")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("varchar(5)");

                    b.HasKey("Id");

                    b.ToTable("extensions", "gkp");
                });

            modelBuilder.Entity("Gatekeeper.Models.Holiday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Createdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Createuser")
                        .HasColumnType("varchar(45)");

                    b.Property<DateTime?>("Holidaydate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Holidayname")
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime?>("Moddate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Moduser")
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Status")
                        .HasColumnType("varchar(5)");

                    b.HasKey("Id");

                    b.ToTable("holidays", "gkp");
                });

            modelBuilder.Entity("Gatekeeper.Models.LkCity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Createdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Createuser")
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Detail")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Status")
                        .HasColumnType("varchar(5)");

                    b.HasKey("Id");

                    b.ToTable("lk_city", "gkp");
                });

            modelBuilder.Entity("Gatekeeper.Models.LkExtension", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Createdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Createuser")
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Detail")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Status")
                        .HasColumnType("varchar(5)");

                    b.HasKey("Id");

                    b.ToTable("lk_extensions", "gkp");
                });

            modelBuilder.Entity("Gatekeeper.Models.LkLocationsearch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Createdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Createuser")
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Detail")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Status")
                        .HasColumnType("varchar(5)");

                    b.HasKey("Id");

                    b.ToTable("lk_locationsearch", "gkp");
                });

            modelBuilder.Entity("Gatekeeper.Models.LkMytaskstatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Createdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Createuser")
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Detail")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Status")
                        .HasColumnType("varchar(5)");

                    b.HasKey("Id");

                    b.ToTable("lk_mytaskstatus", "gkp");
                });

            modelBuilder.Entity("Gatekeeper.Models.LkPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Createdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Createuser")
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Detail")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Status")
                        .HasColumnType("varchar(5)");

                    b.HasKey("Id");

                    b.ToTable("lk_pages", "gkp");
                });

            modelBuilder.Entity("Gatekeeper.Models.LkPaymenttype", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Createdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Createuser")
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Detail")
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("Sortby")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("varchar(5)");

                    b.HasKey("Id");

                    b.ToTable("lk_paymenttype", "gkp");
                });

            modelBuilder.Entity("Gatekeeper.Models.LkProcessingdeficiency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Createdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Createuser")
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Detail")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Status")
                        .HasColumnType("varchar(5)");

                    b.HasKey("Id");

                    b.ToTable("lk_processingdeficiency", "gkp");
                });

            modelBuilder.Entity("Gatekeeper.Models.LkProvince", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Createdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Createuser")
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Detail")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Status")
                        .HasColumnType("varchar(5)");

                    b.HasKey("Id");

                    b.ToTable("lk_province", "gkp");
                });

            modelBuilder.Entity("Gatekeeper.Models.LkReason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Createdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Createuser")
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Detail")
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("Groupid")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("varchar(5)");

                    b.HasKey("Id");

                    b.ToTable("lk_reason", "gkp");
                });

            modelBuilder.Entity("Gatekeeper.Models.LkReasongroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Createdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Createuser")
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Detail")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Status")
                        .HasColumnType("varchar(5)");

                    b.HasKey("Id");

                    b.ToTable("lk_reasongroup", "gkp");
                });

            modelBuilder.Entity("Gatekeeper.Models.LkRecorddeliverymethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Createdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Createuser")
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Detail")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Status")
                        .HasColumnType("varchar(5)");

                    b.HasKey("Id");

                    b.ToTable("lk_recorddeliverymethod", "gkp");
                });

            modelBuilder.Entity("Gatekeeper.Models.LkRequeststate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Createdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Createuser")
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Detail")
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("Sortby")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("varchar(5)");

                    b.HasKey("Id");

                    b.ToTable("lk_requeststate", "gkp");
                });

            modelBuilder.Entity("Gatekeeper.Models.LkRequesttype", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Createdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Createuser")
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Detail")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Refertype")
                        .HasColumnType("varchar(10)");

                    b.Property<int?>("Sortby")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("varchar(5)");

                    b.HasKey("Id");

                    b.ToTable("lk_requesttypes", "gkp");
                });

            modelBuilder.Entity("Gatekeeper.Models.LkReviewtype", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Createdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Createuser")
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Detail")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Status")
                        .HasColumnType("varchar(5)");

                    b.HasKey("Id");

                    b.ToTable("lk_reviewtypes", "gkp");
                });

            modelBuilder.Entity("Gatekeeper.Models.LkSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Createdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Createuser")
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Section")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Sectiontype")
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("Sortby")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("varchar(5)");

                    b.HasKey("Id");

                    b.ToTable("lk_sections", "gkp");
                });

            modelBuilder.Entity("Gatekeeper.Models.Locationitem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Createdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Createuser")
                        .HasColumnType("varchar(45)");

                    b.Property<int?>("Locationid")
                        .HasColumnType("int");

                    b.Property<string>("Othertext")
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("Requestid")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("varchar(5)");

                    b.HasKey("Id");

                    b.ToTable("locationitems", "gkp");
                });

            modelBuilder.Entity("Gatekeeper.Models.Mytask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Approveby")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("Approvedate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Assignby")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("Assigndate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Closedate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Createtime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Createuser")
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("Fileid")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Moddate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Moduser")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Mytaskstatus")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Notes")
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("Remarks")
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Status")
                        .HasColumnType("varchar(5)");

                    b.Property<int?>("Taskid")
                        .HasColumnType("int");

                    b.Property<int?>("Taskstatusid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("mytasks", "gkp");
                });

            modelBuilder.Entity("Gatekeeper.Models.Odata", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AnalystAssigned")
                        .HasColumnType("varchar(max)");

                    b.Property<int?>("Analystassignedid")
                        .HasColumnType("int");

                    b.Property<string>("ClosedDate")
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime?>("Createdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Createuser")
                        .HasColumnType("varchar(5)");

                    b.Property<string>("FileNumber")
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("Idviewed")
                        .HasColumnType("int");

                    b.Property<string>("IntakeNotes")
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime?>("Moddate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Moduser")
                        .HasColumnType("varchar(5)");

                    b.Property<string>("NewFileNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Personid")
                        .HasColumnType("int");

                    b.Property<string>("PreviousRequests")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("ProcessingDeficiency")
                        .HasColumnType("varchar(max)");

                    b.Property<int?>("Processingdeficiencyid")
                        .HasColumnType("int");

                    b.Property<string>("ReceivedDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordDeliveryMethod")
                        .HasColumnType("varchar(150)");

                    b.Property<int?>("Recorddeliverymethodid")
                        .HasColumnType("int");

                    b.Property<string>("ReferenceNumber")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("RequestDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestDetails")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("RequestDueDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestState")
                        .HasColumnType("varchar(max)");

                    b.Property<int?>("RequestStateid")
                        .HasColumnType("int");

                    b.Property<string>("RequestType")
                        .HasColumnType("varchar(150)");

                    b.Property<int?>("Requesttypeid")
                        .HasColumnType("int");

                    b.Property<string>("TimeFrame")
                        .HasColumnType("varchar(max)");

                    b.HasKey("ID");

                    b.ToTable("odata", "gkp");
                });

            modelBuilder.Entity("Gatekeeper.Models.Oipc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Applicant_initial_submission_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Applicant_rebuttal_submission_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Cpsfilenumber")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("Createdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Createuser")
                        .HasColumnType("varchar(45)");

                    b.Property<DateTime?>("Date_of_compliance_to_order")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_order_received")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_received")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_to_be_completed_by")
                        .HasColumnType("datetime2");

                    b.Property<string>("Decision_number")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("Judicial_date_review")
                        .HasColumnType("datetime2");

                    b.Property<string>("Judicial_review")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("Moddate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Moduser")
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Oipc_file_number")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Oipc_findings")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Order_number")
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("Requestid")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Respondent_initial_submission_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Respondent_rebuttal_submission_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Review_closed_date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Reviewtypeid")
                        .HasColumnType("int");

                    b.Property<string>("Sent_to_inquiry")
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Status")
                        .HasColumnType("varchar(5)");

                    b.Property<DateTime?>("Submission_judicial_review_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Summary_of_decision")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("What_is_at_inquiry")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("What_is_being_reviewed")
                        .HasColumnType("varchar(max)");

                    b.HasKey("Id");

                    b.ToTable("oipc", "gkp");
                });

            modelBuilder.Entity("Gatekeeper.Models.OipcItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Createdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Createuser")
                        .HasColumnType("varchar(45)");

                    b.Property<int?>("Groupid")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Moddate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Moduser")
                        .HasColumnType("varchar(45)");

                    b.Property<int?>("Oipcid")
                        .HasColumnType("int");

                    b.Property<string>("Othertext")
                        .HasColumnType("varchar(250)");

                    b.Property<int?>("Reasonid")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("varchar(5)");

                    b.HasKey("Id");

                    b.ToTable("oipc_items", "gkp");
                });

            modelBuilder.Entity("Gatekeeper.Models.Pageitem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Createdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Createuser")
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Othertext")
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("Pageid")
                        .HasColumnType("int");

                    b.Property<int?>("Requestid")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("varchar(5)");

                    b.HasKey("Id");

                    b.ToTable("pageitems", "gkp");
                });

            modelBuilder.Entity("Gatekeeper.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Authorization")
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime?>("Createdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Createuser")
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(250)");

                    b.Property<int?>("Finalcost")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Moddate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Moduser")
                        .HasColumnType("varchar(45)");

                    b.Property<int?>("Payamount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Paymentdate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Paytypeid")
                        .HasColumnType("int");

                    b.Property<int?>("Requestid")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("varchar(5)");

                    b.HasKey("Id");

                    b.ToTable("payments", "gkp");
                });

            modelBuilder.Entity("Gatekeeper.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alternatephone")
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("City")
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Companyname")
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Country")
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("Createdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Createdby")
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Daytimephone")
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Faxphone")
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Firstname")
                        .HasColumnType("varchar(1000)");

                    b.Property<int?>("Gkpid")
                        .HasColumnType("int");

                    b.Property<string>("Lastname")
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Middlename")
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime?>("Moddate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Moduser")
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Personofinterestfirstname")
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Personofinterestlastname")
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Personofinterestmiddlename")
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Postalcode")
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Previousname")
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Province")
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Remark")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Street")
                        .HasColumnType("varchar(1000)");

                    b.HasKey("Id");

                    b.ToTable("person", "gkp");
                });

            modelBuilder.Entity("Gatekeeper.Models.Requestfee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Createdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Createuser")
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(250)");

                    b.Property<int?>("Estimatedcost")
                        .HasColumnType("int");

                    b.Property<string>("Feewaived")
                        .HasColumnType("varchar(5)");

                    b.Property<int?>("Finalcost")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Moddate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Moduser")
                        .HasColumnType("varchar(45)");

                    b.Property<int?>("Paytypeid")
                        .HasColumnType("int");

                    b.Property<string>("Requested")
                        .HasColumnType("varchar(5)");

                    b.Property<int?>("Requestid")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("varchar(5)");

                    b.HasKey("Id");

                    b.ToTable("requestfees", "gkp");
                });

            modelBuilder.Entity("Gatekeeper.Models.Requestfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Analystassignedid")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Archivedate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Closedate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Createdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Createuser")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Feepayment")
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Filenumber")
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("Gkpid")
                        .HasColumnType("int");

                    b.Property<int?>("Idviewed")
                        .HasColumnType("int");

                    b.Property<string>("Intakenotes")
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime?>("Moddate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Moduser")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Oipccomment")
                        .HasColumnType("varchar(2000)");

                    b.Property<int?>("Personid")
                        .HasColumnType("int");

                    b.Property<string>("Previousrequests")
                        .HasColumnType("varchar(max)");

                    b.Property<int?>("Processingdeficiency")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Receivedate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Recorddeliverymethodid")
                        .HasColumnType("int");

                    b.Property<string>("Referencenumber")
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("Remarks")
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime?>("Requestdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Requestdetails")
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime?>("Requestduedate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Requeststate")
                        .HasColumnType("int");

                    b.Property<int?>("Requesttypeid")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Timeframe")
                        .HasColumnType("varchar(max)");

                    b.Property<int?>("Yearid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("requestfiles", "gkp");
                });

            modelBuilder.Entity("Gatekeeper.Models.Sectionuseditem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Createdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Createuser")
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Othertext")
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("Requestid")
                        .HasColumnType("int");

                    b.Property<int?>("Sectionid")
                        .HasColumnType("int");

                    b.Property<string>("Sectiontype")
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Status")
                        .HasColumnType("varchar(5)");

                    b.HasKey("Id");

                    b.ToTable("sectionuseditems", "gkp");
                });

            modelBuilder.Entity("Gatekeeper.Models.Summarydisclosure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Audiodisclosed")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("Audiodisclosedate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Audioidentified")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("Createdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Createuser")
                        .HasColumnType("varchar(45)");

                    b.Property<DateTime?>("Fileclosedate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Moddate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Moduser")
                        .HasColumnType("varchar(45)");

                    b.Property<DateTime?>("Pagedisclosedate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Pagesdisclosed")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Pagesidentified")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Remarks")
                        .HasColumnType("varchar(max)");

                    b.Property<int?>("Requestid")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Videodisclosed")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("Videodisclosedate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Videoidentified")
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("summarydisclosure", "gkp");
                });

            modelBuilder.Entity("Gatekeeper.Models.Videonote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Analystid")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Createdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Createuser")
                        .HasColumnType("varchar(45)");

                    b.Property<DateTime?>("Enterdate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Moddate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Moduser")
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Notes")
                        .HasColumnType("varchar(max)");

                    b.Property<int?>("Requestid")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Timetaken")
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.ToTable("videonotes", "gkp");
                });
#pragma warning restore 612, 618
        }
    }
}
